name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write  

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Create output directory
        run: mkdir -p ./output

      - name: Generate snake
        uses: Platane/snk@master
        with:
          github_user_name: ${{ github.Wadoodjamal }}
          svg_path: ./output/github-contribution-grid-snake.svg

      - name: Deploy snake
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: main  
          folder: ./output
          token: ${{ secrets.GITHUB_TOKEN }}  # Explicitly pass the token
