name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generate snake
        uses: Platane/snk@master
        with:
          github_user_name: ${{ github.repository_owner }}
          svg_out_path: ./output/github-contribution-grid-snake.svg
          gif_out_path: ./output/github-contribution-grid-snake.gif  
          color_snake: blue 
          color_dots: yellow  
          pixel_size: 10 

      - name: Ensure output directory exists
        run: mkdir -p output

      - name: Clean previous deployment worktree
        run: git worktree prune || true

      - name: Deploy snake animation
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages  
          folder: ./output
          token: ${{ secrets.GITHUB_TOKEN }}
          clean: true
          clean-exclude: |
            README.md
            .gitignore
            LICENSE
            output/
