name: Generate Snake Animation

on:
  schedule:
    # Runs every 12 hours
    - cron: "0 */12 * * *"
  workflow_dispatch: # Allow manual runs

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: Platane/snk@master
        with:
          Wadoodjamal: ${{ github.Wadoodjamal }}
          svg_path: ./output/github-contribution-grid-snake.svg
      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: main #
          folder: ./output #
